@startuml

class Cell {
    -int x
    -int y
    ~Cell(int x, int y)
    ~int getX()
    ~int getY()
    ~setX(int value)
    ~setY(int value)
}
class Tile extends Cell {
    -int value
    -Tile[] mergedFrom
    ~Tile(int x, int y, int value)
    ~Tile(Cell cell, int value)
    ~updatePosition(Cell cell)
    ~int getValue()
    ~Tile[] getMergedFrom()
    ~setMergedFrom(Tile[] tiles)
}

class Grid {
    ~Tile[][] field
    ~Tile[][] undoField
    ~Tile[][] bufferField
    ~Grid(int sizeX, int sizeY)
    ~Cell getRandomAvailableCell()
    ~Cell getAllAvailableCells()
    ~Boolean cellsAvailable()
    ~Boolean cellAvailable(Cell cell)
    ~Boolean cellOccupied(Cell cell)
    ~Tile getCellContent(Cell cell)
    ~Tile getCellContent(int x, int y)
    ~Boolean cellWithinBounds(Cell cell)
    -Boolean isCellWithinBounds(int x, int y)
    ~insertTile(Tile tile)
    ~removeTile(Tile tile)
    ~saveTiles()
    ~prepareToSaveTiles()
    ~revertTiles()
    ~clearGrid()
    ~clearUndoGrid()
}


@enduml